### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by liangxinyu0514** [NUSTM/CPNC#1]
The CSKGCompletion/CPNC-S folder in this project is missing the 'saved' directory, 'evaluate.sh,' and 'train.sh'.

**Comment by Wusiwei0410** [comment]
Sorry for my slow reply.
As for the 'saved' directory, this file would be automatically created during the training process.
In the CPNC-S project, I didn't use the shell to run program. Specifically, I created a run_kbc_subgraph.py file under 'CPNC/CSKGCompletion/CPNC-S/src/' to execute the training program. And the test process also be included in the run_kbc_subgraph.py. Besides, the hyperparameters to execute the run_kbc_subgraph.py also are presented in the readme.md file, see here: 

### > https://github.com/NUSTM/CPNC/tree/main#cpnc-s-model

I advise you to read the readme.md file when you have problems running my model.

**Comment by liangxinyu0514** [comment]
Ok, thank you very much for your code, which is of great help to me！！！
