### ISSUE TITLE
computation resource for kmeans

### ISSUE THREAD

**Issue by qiaoxiaoqiao1** [NUSTM/CPNC#3]
I am running k-means, but when I increase the cluster number to 300, my program gets killed. So I wanted to know how many cpu resources you need for 1200 clusters?

**Comment by Wusiwei0410** [comment]
Well, I use a 128G CPU to run the K-means program, but it is also not enough to run it when the clustering number reaches 1200. So I used the PCA to reduce the dimension of embedding to run the k-means and get the clustering result (latent concept label) of each node. By the way, the embeddings of latent concepts are calculated based on the raw embedding and latent concept label. I hope this could help you.

**Comment by qiaoxiaoqiao1** [comment]
Thanks for your quick reply, could you please share your PCA code?

**Comment by Wusiwei0410** [comment]
I am sorry I don't have time to refactor my code, so I just upload a "K_means_using_PCA_example.py" file into the "NodesClustering" folder in this repo, which is my raw code using PCA to implement K-means. You can see it in [https://github.com/NUSTM/CPNC/blob/main/NodesClustering/K_means_using_PCA_example.py](url).
This code includes all the operations I mentioned in my previous reply.

**Comment by Wusiwei0410** [comment]
By the way, the 'n_components ' in the code is the reducing dimension parameter, you need to choose a proper num of it because it would affect the model's performance and it is also restricted by your CPU resources and the cluster num. So, It is pivotal to choose the num of it when you increase the cluster num.

**Comment by qiaoxiaoqiao1** [comment]
I really appreciate your help.

**Comment by Wusiwei0410** [comment]
No worries. I think I have finished this problem, and I will close this issue.
